"""Kairos compatibility surface.

In this recovered build, only ``brief``, ``channels``, ``cron`` and
``sleep`` map to concrete reference sources. ``proactive`` and ``dream``
remain import-compatible shims that default to disabled behavior.
"""

from __future__ import annotations

# --- core ---
from .core import (
    Feature,
    FeatureGate,
    GateConfig,
    KairosMode,
    KairosState,
    RuntimeGate,
    RuntimeGateResult,
    SessionHistory,
    SessionRecord,
    activate_kairos,
    check_directory_trust,
    deactivate_kairos,
    disable_feature,
    enable_feature,
    enabled_features,
    feature,
    forget_trusted_directory,
    get_assistant_system_prompt_addendum,
    get_feature_gate,
    get_gate_config,
    get_kairos_state,
    is_assistant_forced,
    is_feature_enabled,
    is_kairos_active,
    mark_assistant_forced,
    persist_state,
    remember_trusted_directory,
    restore_state,
    set_gate_config,
    set_kairos_active,
)

# --- proactive ---
from .proactive import (
    TICK_TAG,
    IdleDetector,
    IdleLevel,
    ProactiveSuggestionEngine,
    ProactiveStatus,
    TickDebouncer,
    TickMetrics,
    build_tick_message,
    get_idle_detector,
    get_proactive_system_prompt,
    is_context_blocked,
    is_proactive_active,
    pause_proactive,
    report_agent_action,
    resume_proactive,
    run_proactive_loop,
    set_context_blocked,
    set_proactive_active,
    stop_proactive,
)

# --- sleep ---
from .sleep import (
    CommandQueue,
    QueuedCommand,
    SleepQualityMetrics,
    SleepSessionState,
    WakeOnEvent,
    WakeReason,
    WakeResult,
    WakeTriggerType,
    get_command_queue,
    get_sleep_session_state,
    get_wake_on_event,
    persist_session_dual,
    restore_session,
    sleep_until_wake,
    wake_agent,
    wake_agent_sync,
)

# --- cron ---
from .cron import (
    CronExpr,
    CronJitterConfig,
    CronScheduler,
    CronSchedulerConfig,
    CronStateStore,
    CronTask,
    SchedulerLock,
    SessionCronJob,
    SessionCronManager,
    TaskStore,
    TaskType,
    create_cron_task,
    delete_cron_task,
    list_cron_tasks,
    parse_cron_expression,
)

# --- brief ---
from .inbox import get_inbox_snapshot

from .brief import (
    BRIEF_PROACTIVE_SECTION,
    BriefLevel,
    ConversationDensity,
    ViewMode,
    UserMessage,
    clear_message_history,
    compress_error,
    disable_brief,
    enable_brief,
    filter_messages_for_view,
    format_for_brief_level,
    get_brief_level,
    get_brief_system_prompt,
    get_conversation_density,
    get_message_history,
    get_view_mode,
    is_brief_enabled,
    is_brief_entitled,
    render_send_user_message_payload,
    send_user_message,
    set_brief_level,
    set_view_mode,
    should_render_stream_event,
    should_emit,
    summarize_tool_result,
    toggle_brief,
)

# --- channels ---
from .channels import (
    ChannelEntry,
    ChannelFilter,
    ChannelGateContext,
    ChannelKind,
    ChannelMessage,
    ChannelNotification,
    ChannelPersistence,
    ChannelRegistry,
    FilteredChannelDispatcher,
    FilteredSubscription,
    GateResult,
    deserialize_channel_message,
    gate_channel,
    get_channel_filter_router,
    get_channel_persistence,
    get_channel_registry,
    get_channels_system_prompt,
    has_channel_capability,
    register_channel_from_mcp,
    serialize_channel_message,
)

# --- dream ---
from .dream import (
    DailyLogWriter,
    DreamPhase,
    DreamScheduleConfig,
    DreamTask,
    DreamTurn,
    GateCheckResult,
    NightlyDreamConfig,
    build_consolidation_prompt,
    build_daily_log_prompt,
    check_dream_gates,
    create_dream_cron_task,
    get_daily_log_path,
    get_dream_task,
    get_memory_dir,
    get_next_dream_time,
    is_dream_running,
    kill_dream,
    list_dream_tasks,
    record_consolidation,
    register_dream,
    run_nightly_dream,
    trigger_dream_from_kairos,
)

__all__ = [
    # core
    "Feature",
    "FeatureGate",
    "GateConfig",
    "KairosMode",
    "KairosState",
    "RuntimeGate",
    "RuntimeGateResult",
    "SessionHistory",
    "SessionRecord",
    "activate_kairos",
    "check_directory_trust",
    "deactivate_kairos",
    "disable_feature",
    "enable_feature",
    "enabled_features",
    "feature",
    "forget_trusted_directory",
    "get_assistant_system_prompt_addendum",
    "get_feature_gate",
    "get_gate_config",
    "get_kairos_state",
    "is_assistant_forced",
    "is_feature_enabled",
    "is_kairos_active",
    "mark_assistant_forced",
    "persist_state",
    "remember_trusted_directory",
    "restore_state",
    "set_gate_config",
    "set_kairos_active",
    # proactive
    "TICK_TAG",
    "IdleDetector",
    "IdleLevel",
    "ProactiveSuggestionEngine",
    "ProactiveStatus",
    "TickDebouncer",
    "TickMetrics",
    "build_tick_message",
    "get_idle_detector",
    "get_proactive_system_prompt",
    "is_context_blocked",
    "is_proactive_active",
    "pause_proactive",
    "report_agent_action",
    "resume_proactive",
    "run_proactive_loop",
    "set_context_blocked",
    "set_proactive_active",
    "stop_proactive",
    # sleep
    "CommandQueue",
    "QueuedCommand",
    "SleepQualityMetrics",
    "SleepSessionState",
    "WakeOnEvent",
    "WakeReason",
    "WakeResult",
    "WakeTriggerType",
    "get_command_queue",
    "get_sleep_session_state",
    "get_wake_on_event",
    "persist_session_dual",
    "restore_session",
    "sleep_until_wake",
    "wake_agent",
    "wake_agent_sync",
    # cron
    "CronExpr",
    "CronJitterConfig",
    "CronScheduler",
    "CronSchedulerConfig",
    "CronStateStore",
    "CronTask",
    "SchedulerLock",
    "SessionCronJob",
    "SessionCronManager",
    "TaskStore",
    "TaskType",
    "create_cron_task",
    "delete_cron_task",
    "list_cron_tasks",
    "parse_cron_expression",
    # brief
    "BRIEF_PROACTIVE_SECTION",
    "BriefLevel",
    "ConversationDensity",
    "ViewMode",
    "UserMessage",
    "clear_message_history",
    "compress_error",
    "disable_brief",
    "enable_brief",
    "filter_messages_for_view",
    "format_for_brief_level",
    "get_brief_level",
    "get_brief_system_prompt",
    "get_conversation_density",
    "get_message_history",
    "get_view_mode",
    "is_brief_enabled",
    "is_brief_entitled",
    "render_send_user_message_payload",
    "send_user_message",
    "set_brief_level",
    "set_view_mode",
    "should_render_stream_event",
    "should_emit",
    "summarize_tool_result",
    "toggle_brief",
    # channels
    "ChannelEntry",
    "ChannelFilter",
    "ChannelGateContext",
    "ChannelKind",
    "ChannelMessage",
    "ChannelNotification",
    "ChannelPersistence",
    "ChannelRegistry",
    "FilteredChannelDispatcher",
    "FilteredSubscription",
    "GateResult",
    "deserialize_channel_message",
    "gate_channel",
    "get_channel_filter_router",
    "get_channel_persistence",
    "get_channel_registry",
    "get_channels_system_prompt",
    "has_channel_capability",
    "register_channel_from_mcp",
    "serialize_channel_message",
    # inbox
    "get_inbox_snapshot",
    # dream
    "DailyLogWriter",
    "DreamPhase",
    "DreamScheduleConfig",
    "DreamTask",
    "DreamTurn",
    "GateCheckResult",
    "NightlyDreamConfig",
    "build_consolidation_prompt",
    "build_daily_log_prompt",
    "check_dream_gates",
    "create_dream_cron_task",
    "get_daily_log_path",
    "get_dream_task",
    "get_memory_dir",
    "get_next_dream_time",
    "is_dream_running",
    "kill_dream",
    "list_dream_tasks",
    "record_consolidation",
    "register_dream",
    "run_nightly_dream",
    "trigger_dream_from_kairos",
]
