"""Buddy — companion sprites, prompts, terminal UI, /buddy command."""

from .command import BuddyCommand
from .companion import (
    clear_roll_cache,
    companion_user_id,
    get_companion,
    hatch_companion,
    roll,
    roll_with_seed,
)
from .nurture import NurtureEngine
from .observer import CompanionObserver
from .prompt import companion_intro_text, get_companion_intro_attachment
from .sprites import BODIES, HAT_LINES, render_face, render_sprite, sprite_frame_count
from .types import (
    EYES,
    HATS,
    RARITIES,
    RARITY_COLORS,
    RARITY_STARS,
    RARITY_WEIGHTS,
    SPECIES,
    STAT_NAMES,
    Companion,
    CompanionBones,
    CompanionSoul,
    Eye,
    Hat,
    Rarity,
    Species,
    StatName,
    StoredCompanion,
    axolotl,
    blob,
    cactus,
    capybara,
    cat,
    chonk,
    dragon,
    duck,
    ghost,
    goose,
    mushroom,
    octopus,
    owl,
    penguin,
    rabbit,
    robot,
    snail,
    turtle,
)
from .ui_terminal import (
    CompanionRenderState,
    companion_reserved_columns,
    render_companion,
    run_animation_loop,
)

__all__ = [
    "BODIES",
    "BuddyCommand",
    "Companion",
    "CompanionBones",
    "CompanionObserver",
    "CompanionRenderState",
    "CompanionSoul",
    "EYES",
    "HATS",
    "HAT_LINES",
    "NurtureEngine",
    "RARITIES",
    "RARITY_COLORS",
    "RARITY_STARS",
    "RARITY_WEIGHTS",
    "SPECIES",
    "STAT_NAMES",
    "Eye",
    "Hat",
    "Rarity",
    "Species",
    "StatName",
    "StoredCompanion",
    "axolotl",
    "blob",
    "cactus",
    "capybara",
    "cat",
    "chonk",
    "clear_roll_cache",
    "companion_intro_text",
    "companion_reserved_columns",
    "companion_user_id",
    "dragon",
    "duck",
    "get_companion",
    "get_companion_intro_attachment",
    "ghost",
    "goose",
    "hatch_companion",
    "mushroom",
    "octopus",
    "owl",
    "penguin",
    "rabbit",
    "render_companion",
    "render_face",
    "render_sprite",
    "robot",
    "roll",
    "roll_with_seed",
    "run_animation_loop",
    "snail",
    "sprite_frame_count",
    "turtle",
]
