// Command modules
pub mod auth_commands;
pub mod autohand_commands;
pub mod chat_history_commands;
pub mod chat_migration_commands;
pub mod cli_commands;
pub mod dashboard_commands;
pub mod file_commands;
pub mod indexer_commands;
pub mod git_commands;
pub mod llm_commands;
pub mod menu_commands;
pub mod project_commands;
pub mod prompt_commands;
pub mod session_commands;
pub mod settings_commands;
pub mod sub_agent_commands;
pub mod docs_commands;

// Re-export all command functions for easy access
pub use auth_commands::*;
pub use autohand_commands::*;
pub use chat_history_commands::*;
pub use chat_migration_commands::*;
pub use cli_commands::*;
pub use dashboard_commands::*;
pub use file_commands::*;
pub use indexer_commands::*;
pub use git_commands::*;
pub use llm_commands::*;
pub use menu_commands::*;
pub use project_commands::*;
pub use prompt_commands::*;
pub use session_commands::*;
pub use settings_commands::*;
pub use sub_agent_commands::*;
pub use docs_commands::*;
