// Service-specific tests
pub mod agent_registry;
pub mod app_settings;
pub mod auth_service;
pub mod autohand_acp;
pub mod autohand_rpc;
pub mod file_service;
pub mod git_service_enhanced;
pub mod hooks_service;
pub mod project_sidebar_actions;
pub mod prompt_service;
pub mod recent_projects;
